### ISSUE TITLE
Media-Mixins not working anymore

### ISSUE THREAD

**Issue by mhbapcc** [ConnectThink/WP-SCSS#163]
Hello, since I've updated to 2.0.x all my scss media-mixins don't work anymore. Log says "mixin not defined", although they are defined: 

```
@mixin m {
    @media only screen and (max-width: 767px) {
        @content;
    }
}

h1 {
    font-size: 42px;

    @include m {
        font-size: 38px;
    }
}
```
Updated my DB as mentioned in [#157](https://github.com/ConnectThink/WP-SCSS/issues/157). Anybody expecting similar issues?

**Comment by shadoath** [comment]
Turns out I had made a mistake with the SVN WordPress repo and didn't upload all the files for the new ScssPhp update in version 2.0.0. This has now been corrected in version 2.1.1

**Comment by mhbapcc** [comment]
Thanks for your quick action. Unfortunately I'm having still problems. This scss code...
```
.site-title {
    &__inner {
        button[data-toggle-action="window-back"] {
            margin: 0
        }
    )
)
```
...leads to this css code...
```
.site-title__innerÂ  button[data-toggle-action="window-back"]{margin:0}
```
Maybe problems with unicode or html encoding issues?

**Comment by shadoath** [comment]
I see two closing `)` That may be typos. I ran the following scss:
```
.site-title {
  &__inner {
    button[data-toggle-action="window-back"] {
      margin: 0
    }
  }
}
```
And it compiled down to:
``` 
.site-title__inner button[data-toggle-action="window-back"] {
  margin: 0;
}
```
Maybe this is more of an encoding issue in your files, something like [this post](https://stackoverflow.com/questions/11001682/special-char-added-to-css-%C3%A2%E2%82%AC-where-did-this-come-from).  Are you moving between Windows/Linux environments? 
Try adding `@charset "UTF-8";` to the top of the scss file

**Comment by mhbapcc** [comment]
Oops. This happened while I was formatting the scss code in github (that's not the problem). `@charset "UTF-8";` did not fix the problem. But I just found out that there was an HTML space (`&nbsp;`) after the `&__inner` class. In the previous versions this was probably decoded differently.
